baseURL = "https://kulics.github.io/"
title = "kulics"
theme = "hugo-coder"

languageCode = "zh"
defaultContentLanguage = "zh"

paginate = 20

pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Kulics"
    info = "Normal Developer"
    description = "Kulics' personal website"
    keywords = "blog,developer,personal"
    avatarURL = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Open thinking."

    hidecredits = false
    hidecopyright = false

    dateFormat = "January 2, 2006"
    since = 2019

    rtl = false

    math = true
    maxSeeAlsoItems = 5
    colorScheme = "auto"
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/kulics/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/kulicswu/"

[[menu.main]]
name = "Posts"
weight = 1
url = "posts/"

[[menu.main]]
name = "About"
weight = 2
url = "about/"

[[menu.main]]
name = "Projects"
weight = 3
url = "projects/"